---
name: Build an Push Docker Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: kluw-vault
      PROJECT_ID: kluw-vault
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
    
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest europe-north1-docker.pkg.dev/$PROJECT_ID/personal-docker-repository/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest europe-north1-docker.pkg.dev/$PROJECT_ID/personal-docker-repository/$IMAGE_NAME:$GIT_TAG
        docker push europe-north1-docker.pkg.dev/$PROJECT_ID/personal-docker-repository/$IMAGE_NAME:latest
        docker push europe-north1-docker.pkg.dev/$PROJECT_ID/personal-docker-repository/$IMAGE_NAME:$GIT_TAG